service: mapshot-image-lambda

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 4096
  timeout: 30
  region: ap-northeast-2
functions:
  prod:
    handler: src/index.handler
    events:
      - http:
        path: /lambda
        method: get
  dev:
    handler: src/index.handler
    events:
      - http:
        path: /lambda-dev
        method: get