service: mapshot-image-lambda

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 700
  timeout: 30
  region: ap-northeast-2
functions:
  start:
    handler: src/index.handler
    events:
      - http:
          path: /lambda
          method: get